# Generated by Django 3.0 on 2020-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('link', models.CharField(max_length=2500)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
