# Generated by Django 3.0 on 2020-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200118_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='info',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(max_length=10000),
        ),
    ]
