# Generated by Django 3.0 on 2020-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200118_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='info',
            new_name='info_nl',
        ),
        migrations.AddField(
            model_name='video',
            name='info_en',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
