# Generated by Django 3.0.2 on 2020-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
        ('videos', '0005_auto_20200301_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='work',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.Work'),
        ),
    ]
