# Generated by Django 3.0 on 2020-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('l_art_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_art_cat_l1', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('l_art_cat_l2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'l_art_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('l_art_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_art_type_l1', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('l_art_type_l2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'l_art_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_m_nr', models.IntegerField(blank=True, null=True)),
                ('art_title_l1', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('art_title_l2', models.CharField(blank=True, max_length=150, null=True)),
                ('art_serie_id', models.IntegerField(blank=True, null=True)),
                ('art_expo_id', models.IntegerField(blank=True, null=True)),
                ('art_material_l1', models.CharField(blank=True, max_length=255, null=True, verbose_name='materials')),
                ('art_material_l2', models.CharField(blank=True, max_length=150, null=True)),
                ('art_dimension', models.CharField(blank=True, max_length=50, null=True, verbose_name='dimension')),
                ('art_date', models.DateField(max_length=255, null=True, verbose_name='date')),
                ('art_info_l1', models.TextField(blank=True, null=True, verbose_name='info')),
                ('art_info_l2', models.TextField(blank=True, null=True)),
                ('art_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='price')),
                ('art_sold', models.BooleanField(blank=True, null=True, verbose_name='sold')),
                ('art_sold_to_date', models.DateTimeField(blank=True, null=True)),
                ('art_sold_to_id', models.IntegerField(blank=True, null=True)),
                ('art_filename', models.FileField(help_text='Merk op dat een plaatje op de website getoons wordt op de grootte die je upload (zie hieronder als voorbeeld)', null=True, upload_to='images', verbose_name='image')),
                ('art_publish', models.BooleanField(null=True, verbose_name='published?')),
                ('art_designer', models.CharField(blank=True, max_length=255, null=True)),
                ('art_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('art_artist_worked_with', models.TextField(blank=True, null=True, verbose_name='collaborators')),
                ('art_owned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('art_sold_info', models.TextField(blank=True, null=True)),
                ('art_anecdote_publish', models.BooleanField(blank=True, null=True, verbose_name='anecdote_published?')),
                ('art_anecdote_l1', models.TextField(blank=True, null=True, verbose_name='anecdote')),
                ('art_anecdote_l2', models.TextField(blank=True, null=True)),
                ('art_equipment', models.TextField(blank=True, null=True)),
                ('art_viewable', models.IntegerField(blank=True, null=True)),
                ('art_view_location', models.CharField(blank=True, max_length=255, null=True)),
                ('art_view_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'library_art',
                'managed': False,
            },
        ),
    ]
