# Generated by Django 3.0 on 2020-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('expo_id', models.AutoField(primary_key=True, serialize=False)),
                ('expo_type_id', models.IntegerField(blank=True, null=True)),
                ('expo_name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('expo_place_id', models.IntegerField(blank=True, null=True)),
                ('expo_startdate', models.DateTimeField(null=True, verbose_name='start date')),
                ('expo_enddate', models.DateTimeField(null=True, verbose_name='end date')),
                ('expo_info_l1', models.TextField(blank=True, null=True, verbose_name='info')),
                ('expo_info_l2', models.TextField(blank=True, null=True)),
                ('expo_publish', models.BooleanField(null=True, verbose_name='published?')),
            ],
            options={
                'db_table': 'library_expo',
                'managed': False,
            },
        ),
    ]
