# Generated by Django 3.0 on 2020-04-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_nl', models.TextField(default='hallo meiden!', max_length=150000)),
                ('text_en', models.TextField(default='hello girls!', max_length=150000)),
            ],
        ),
    ]
